apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: webapp-config
    literals:
      - APP_NAME=WebApplication
      - LOG_LEVEL=INFO
      - ENVIRONMENT=base

secretGenerator:
  - name: webapp-secret
    literals:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=MyPassword123